name: reviewdog2
on:
  push:
    branches:
      - master
  pull_request:
  

jobs:
  reviewdog-github-check:
    if: github.event_name == 'push'
    name: reviewdog (github-check)
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Terraform init'
        run: terraform init
      
      - name: pwd test
        run: echo $(pwd)
      - name: PWD test
        run: echo $PWD
      - name: GITHUB_WORKSPACE
        run: echo $GITHUB_WORKSPACE 
            
      - name: 'Setup Reviewdog'
        run: |
         mkdir -p $HOME/bin && curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $HOME/bin
         echo ::add-path::$HOME/bin
         
      - name: 'Run ReviewDog (github-check)'
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker run --rm --name TFLint -v $GITHUB_WORKSPACE:/data -t wata727/tflint --format=checkstyle | reviewdog -f=checkstyle -name="github-check" -reporter=github-check -level=warning -filter-mode=nofilter
          
  reviewdog-pr:
    if: github.event_name == 'pull_request'
    name: reviewdog on Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Terraform init'
        run: terraform init
            
      - name: 'Setup reviewdog'
        run: |
         mkdir -p $HOME/bin && curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $HOME/bin
         echo ::add-path::$HOME/bin
         
      - name: Run reviewdog (github-pr-check)
        continue-on-error: true
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker run --rm --name TFLint -v $GITHUB_WORKSPACE:/data -t wata727/tflint --format=checkstyle | reviewdog -f=checkstyle -reporter=github-pr-check -name=github-pr-check-info -fail-on-error
          
      - name: Run reviewdog (github-pr-check with fail-on-error)  
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker run --rm --name TFLint -v $GITHUB_WORKSPACE:/data -t wata727/tflint --format=checkstyle | reviewdog -f=checkstyle -name=pr-check-fail-on-error -reporter=github-pr-check -fail-on-error -filter-mode=nofilter 
  Checkov-check:
    name: Checkov (github-check)
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
         
      - name: Run Checkov CLI test
        continue-on-error: true
        run: docker run --rm --name Checkov -v $GITHUB_WORKSPACE:/tf bridgecrew/checkov -d /tf -o cli
